name: Setup Environment

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to install'
        required: true
        default: '16'
        type: string
      install_dependencies:
        description: 'Whether to install dependencies (true/false as string)'
        required: false
        default: 'true'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        if: ${{ inputs.install_dependencies == 'true' }}
        run: |
          echo "Installing dependencies..."
          npm install
